# frozen_string_literal: true

module Pinnacle
  module Types
    module DlcCampaignUseCaseEnum
      extend Pinnacle::Internal::Types::Enum

      ACCOUNT_NOTIFICATION = "ACCOUNT_NOTIFICATION"
      AGENTS_FRANCHISES = "AGENTS_FRANCHISES"
      CARRIER_EXEMPT = "CARRIER_EXEMPT"
      CHARITY = "CHARITY"
      CUSTOMER_CARE = "CUSTOMER_CARE"
      DELIVERY_NOTIFICATION = "DELIVERY_NOTIFICATION"
      EMERGENCY = "EMERGENCY"
      FRAUD_ALERT = "FRAUD_ALERT"
      HIGHER_EDUCATION = "HIGHER_EDUCATION"
      K_12_EDUCATION = "K12_EDUCATION"
      LOW_VOLUME = "LOW_VOLUME"
      M_2_M = "M2M"
      MARKETING = "MARKETING"
      MIXED = "MIXED"
      POLITICAL = "POLITICAL"
      POLLING_VOTING = "POLLING_VOTING"
      PROXY = "PROXY"
      PUBLIC_SERVICE_ANNOUNCEMENT = "PUBLIC_SERVICE_ANNOUNCEMENT"
      SECURITY_ALERT = "SECURITY_ALERT"
      SOCIAL = "SOCIAL"
      SOLE_PROPRIETOR = "SOLE_PROPRIETOR"
      SWEEPSTAKE = "SWEEPSTAKE"
      TRIAL = "TRIAL"
      TWO_FA = "TWO_FA"
      UCAAS_HIGH = "UCAAS_HIGH"
      UCAAS_LOW = "UCAAS_LOW"
    end
  end
end
