# frozen_string_literal: true

module Pinnacle
  module Types
    module RcsCampaignUseCaseEnum
      extend Pinnacle::Internal::Types::Enum

      ADVERTISING_MARKETING = "ADVERTISING_MARKETING"
      ARTS_AND_ENTERTAINMENT = "ARTS_AND_ENTERTAINMENT"
      BFSI = "BFSI"
      COMMERCIAL_AND_INDUSTRIAL = "COMMERCIAL_AND_INDUSTRIAL"
      COMMUNITY_ORGANIZATIONS = "COMMUNITY_ORGANIZATIONS"
      CREDIT_RATING = "CREDIT_RATING"
      DELIVERY_PARTNER = "DELIVERY_PARTNER"
      EDUCATION = "EDUCATION"
      FINANCE = "FINANCE"
      FOOD_AND_BEVERAGE = "FOOD_AND_BEVERAGE"
      GAMING = "GAMING"
      GOVERNMENT = "GOVERNMENT"
      HEALTH = "HEALTH"
      HOTEL_AND_BNB = "HOTEL_AND_BNB"
      INSURANCE = "INSURANCE"
      LEGAL = "LEGAL"
      LENDING = "LENDING"
      LOANS = "LOANS"
      LOCAL_SERVICES = "LOCAL_SERVICES"
      NEWS = "NEWS"
      NON_GOVERNMENTAL_ORGANIZATIONS = "NON_GOVERNMENTAL_ORGANIZATIONS"
      NON_PROFIT_ORGANIZATIONS = "NON_PROFIT_ORGANIZATIONS"
      ONLINE_SELLER = "ONLINE_SELLER"
      OTHER = "OTHER"
      PRODUCTIVITY = "PRODUCTIVITY"
      PROPERTY = "PROPERTY"
      SCIENCE_TECHNOLOGY_ENGINEERING = "SCIENCE_TECHNOLOGY_ENGINEERING"
      SHOPPING_AND_RETAIL = "SHOPPING_AND_RETAIL"
      SOCIAL = "SOCIAL"
      SPORTS = "SPORTS"
      TELECOMMUNICATIONS = "TELECOMMUNICATIONS"
      TRAVEL = "TRAVEL"
      UTILITIES = "UTILITIES"
    end
  end
end
