# frozen_string_literal: true

require_relative "../../tools/client"
require_relative "file_uploader"

module Pinnacle
  module Tools
    # Enhanced Tools client that uses FileUploader instead of FileClient
    # Extends the autogenerated Tools::Client to provide upload_from_path functionality
    class EnhancedClient
      # @return [Pinnacle::Tools::UrlClient]
      attr_reader :url
      # @return [Pinnacle::Tools::FileUploader]
      attr_reader :file
      # @return [Pinnacle::Tools::ContactCardClient]
      attr_reader :contact_card

      # @param request_client [Pinnacle::RequestClient]
      # @return [Pinnacle::Tools::EnhancedClient]
      def initialize(request_client:)
        @url = Pinnacle::Tools::UrlClient.new(request_client: request_client)
        @file = Pinnacle::Tools::FileUploader.new(request_client: request_client)
        @contact_card = Pinnacle::Tools::ContactCardClient.new(request_client: request_client)
      end
    end

    # Async version of EnhancedClient
    class AsyncEnhancedClient
      # @return [Pinnacle::Tools::AsyncUrlClient]
      attr_reader :url
      # @return [Pinnacle::Tools::AsyncFileUploader]
      attr_reader :file
      # @return [Pinnacle::Tools::AsyncContactCardClient]
      attr_reader :contact_card

      # @param request_client [Pinnacle::AsyncRequestClient]
      # @return [Pinnacle::Tools::AsyncEnhancedClient]
      def initialize(request_client:)
        @url = Pinnacle::Tools::AsyncUrlClient.new(request_client: request_client)
        @file = Pinnacle::Tools::AsyncFileUploader.new(request_client: request_client)
        @contact_card = Pinnacle::Tools::AsyncContactCardClient.new(request_client: request_client)
      end
    end
  end
end
