# frozen_string_literal: true

module Pinnacle
  # Additional subcategories for the primary use case.
  class SubUseCaseEnum
    ACCOUNT_NOTIFICATION = "ACCOUNT_NOTIFICATION"
    CUSTOMER_CARE = "CUSTOMER_CARE"
    DELIVERY_NOTIFICATION = "DELIVERY_NOTIFICATION"
    FRAUD_ALERT = "FRAUD_ALERT"
    HIGHER_EDUCATION = "HIGHER_EDUCATION"
    MARKETING = "MARKETING"
    POLLING_VOTING = "POLLING_VOTING"
    PUBLIC_SERVICE_ANNOUNCEMENT = "PUBLIC_SERVICE_ANNOUNCEMENT"
    SECURITY_ALERT = "SECURITY_ALERT"
    TWO_FA = "TWO_FA"
  end
end
