# frozen_string_literal: true

require_relative "pinnacle/types/check_rcs_capability_response"
require_relative "pinnacle/types/receive_rcs_messages_response"
require_relative "pinnacle/types/rcs_message"
require_relative "pinnacle/types/sms_message"
require_relative "pinnacle/types/send_an_rcs_message_request_body"
require_relative "pinnacle/types/rcs_message_sent"
require_relative "pinnacle/types/sms_message_sent"
require_relative "pinnacle/types/send_an_rcs_message_response"
require_relative "pinnacle/types/sms_message_message"
require_relative "pinnacle/types/rcs_message_message_type"
require_relative "pinnacle/types/sms_message_sent_status"
require_relative "pinnacle/types/action_action_type"
require_relative "pinnacle/types/action"
require_relative "pinnacle/types/card_style_payload_image_alignment"
require_relative "pinnacle/types/card_style_payload_media_height"
require_relative "pinnacle/types/card_style_payload_width"
require_relative "pinnacle/types/card_style_payload_orientation"
require_relative "pinnacle/types/card_style_payload"
require_relative "pinnacle/types/card_payload"
require_relative "pinnacle/types/message_payload_media_type"
require_relative "pinnacle/types/message_payload"
